### ISSUE TITLE
Install R-devel version

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#118]
Hi @tatarsky , I was trying to install the R-devel verion on the cluster (R 3.3 and R 3.4), because some package I wanna use is built under R-3.3. I came across this err

```
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking if zlib version >= 1.2.5... no
checking whether zlib support suffices... configure: error: zlib library and headers are required
```

It looks like our zlib version is old, it's 1.2.3. So I install the zlib 1.2.8 under my own directory  `/frazer01/home/hel070/zlib`, but I don't know how to specify the path to use the new version of zlib when installing R-devel. I have tried specify the path of `LD_LIBRARY_PATH to /frazer01/home/hel070/zlib/lib` and `PKG_CONFIG_PATH to /frazer01/home/hel070/zlib/lib/pkgconfig`, but they didn't work. 
when I do `whereis zlib`, it still gives me `zlib: /usr/include/zlib.h /usr/share/man/man3/zlib.3.gz`

Could you instruct me how I should proceed?

Thanks,
Hurley

**Comment by tatarsky** [comment]
LD_LIBRARY_PATH has nothing to do with compilation options. 

I assume you are typing a `configure` command there. Do:

`configure --help` and look for any options to manually instruct the configure autoconf to use your copy of the zlib. 

Or provide the full path to your work area and I will look for you.

**Comment by hurleyLi** [comment]
here's the configure file`/frazer01/home/hel070/R-devel/configure`. there're quite a few options related to library path, not sure which one to use.

**Comment by tatarsky** [comment]
The short answer due to being busy is there is no specific zlib configure flag but you can use the standard CPPFLAGS/ LDFLAGS environment vars to override or add to the search path. Normally you set those to something like given your example zlib location;

```
export LDFLAGS='-L/frazer01/home/hel070/zlib/lib'
export CPPFLAGS='-I/frazer01/home/hel070/zlib/include'
```

Note in case it doesn't come across well thats a "dash capital I"

Then try your configure. You may need a couple of passes/variations of the above but that should point you in the right direction.

**Comment by hurleyLi** [comment]
The installation doesn't give error on zlib now. But another error raises, it complains the version of bzip2..

```
checking for BZ2_bzlibVersion in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking if bzip2 version >= 1.0.6... no
checking whether bzip2 support suffices... configure: error: bzip2 library and headers are required
```

Our version on the cluster is 1.0.5, could you please update the bzip2 version on the cluster. 
Or I do have the new version install in /frazer01/home/hel070/bzip2, how should I set the path or etc?
thansk

**Comment by tatarsky** [comment]
System software is at the levels supported by the distro via RPM and will not be altered above that revision due to dependencies in the system software. In other words, no I will not (and cannot) update the default bzip2 version.

If you wish modules to have newer versions you can request them or build your own. As you are building by your own statement a "newer R" this may require that work be done. 

I did notice a moment ago for example we already have a zlib tree in /software/zlib-1.2.8. A similar one could be done for bzip.

Same drill then if you wish to compile newer code sometimes you need to build all the dependencies and feed the configure options to use the other paths.

**Comment by tatarsky** [comment]
I will add BTW having done this many many times I am more than willing just to build you an R-3.3 module you can just use. But if you truly want the thrill of it, by all means feel free (to build your own)

**Comment by hurleyLi** [comment]
Yes, a R-3.3 module sounds better than me trying to install it.

**Comment by tatarsky** [comment]
I will work on it tomorrow morning.

**Comment by tatarsky** [comment]
To clarify one item: R-devel is 3.4. R 3.3 is about to be released. I will based on a quick scan of what you were looking at build R-devel which is 3.4 as a module. 

```
cat VERSION
3.4.0 Under development (unstable)
```

But it is NOT the same as the R-3.3 release which I believe is in pre-release.

I believe those sources are here:

https://cran.r-project.org/src/base-prerelease/

If you need R 3.3 v.s. R-devel (3.4) advise. For now I'll assume 3.4.

**Comment by tatarsky** [comment]
Initial draft of R-devel (aka 3.4) almost done. Out of curiosity doing one for R-alpha (aka 3.3) as well.

**Comment by tatarsky** [comment]
@cdeboever3 I believe I need to work with you to make sure modulefiles git commits are correct. I dimly recall last time I did one I messed up your scheme. Feel free to email me if I am off base.

**Comment by tatarsky** [comment]
```
$ module add R/3.4.0
$ R
R Under development (unstable) (2016-03-28 r70390) -- "Unsuffered Consequences"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
>
```

Tell me if it works or doesn't work. Working on one for 3.3 just for grins.

**Comment by tatarsky** [comment]
```
$ module add R/3.3.0
$ R
R version 3.3.0 alpha (2016-03-28 r70390)
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

Will leave both there for now. No extra system level libraries added. Happy to do so with a list.

**Comment by hurleyLi** [comment]
Thanks Paul! It works well. And I can commit these modules to git.

**Comment by hurleyLi** [comment]
Module change pushed to git. I'll close this issue. Thanks again!
