### ISSUE TITLE
install devtools in R-3.3.0

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#125]
Hi @tatarsky, 

I'm trying to install the _devtools_ packages in R-3.3.0, which requires the _git2r_ pakcage. But I always got this error no matter how I tried to install it

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/frazer01/software/R-3.3.0/lib64/R/library/git2r/libs/git2r.so':
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/frazer01/software/R-3.3.0/lib64/R/library/git2r’
```

I downloaded the packages from here
https://cran.r-project.org/src/contrib/devtools_1.10.0.tar.gz
https://cran.r-project.org/src/contrib/git2r_0.14.0.tar.gz

Thanks,
Hurley

**Comment by tatarsky** [comment]
I had no such issue but you've only provided the last part of what you did so I'm not sure whats involved in the error above. It is odd its asking for "libssl.so.1.0.0" so precisely as no such concept exists in RHEL. It feels like you are showing me a build on a system that wasn't RHEL. 

Or its possible what is really happening above is it is because I do not grant write permission to a shared tree. But I simply added as root the modules to the 3.3.0 tree:

```
$ module load R/3.3.0
$ R CMD INSTALL  git2r_0.14.0.tar.gz
(builds installs no errors of that kind)
$ R CMD INSTALL  devtools_1.10.0.tar.gz 
(builds installs no errors of that kind)
$ R
R version 3.3.0 alpha (2016-03-28 r70390)
> library("devtools")
> library("git2r")
>
```

So I'm happy to add R modules at request or provide more of what you did to get that error. 

Note the command above (R CMD INSTALL) also takes an alternate locate for files with the -l flag.

Aka:

```
R CMD INSTALL -l (some path where I want to install things) (tar ball)
```

Which may be useful.

**Comment by hurleyLi** [comment]
Thanks for the installation Paul!
