### ISSUE TITLE
Confirming layout plans of /frazer01/software

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#17]
I was going to build a few of the packages referenced in #15 as:

/frazer01/software/package-X.Y.Z

I assume that is the plan. Advise if it is not.

**Comment by hirokomatsui** [comment]
I agree with that. We will have duplicate packages in that way, be able to manage the path with module.

**Comment by tatarsky** [comment]
OK. Cool. I tend to also place a "README.BUILD" in the top level with any local arguments or dependencies. I'm moving along on this #15 request. I'll see where it goes.

**Comment by tatarsky** [comment]
Oh, and I build as non-root as root builds sometimes want to write in weird places. This item just tried to add items to /etc.

**Comment by cdeboever3** [comment]
[I wrote some instructions on the wiki for adding software](https://github.com/frazer-lab/cluster/wiki/Frazer-Lab-Cluster-User-Guide#installing-software) to /frazer01/software/ that you can reference. I added a note about not building as root and leaving a README.BUILD. Feel free to edit the wiki. I try to be as explicit as possible because we will have people coming onto the cluster with little prior computational experience.

**Comment by tatarsky** [comment]
Ah nice.
