### ISSUE TITLE
RAM Limit on head nodes

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#179]
This mainly came up as Terry was trying to run a job that needed more than 10GB of RAM, and needed to access the internet.

@nariai seemed to think that there is a simple bash command that would bypass the limit for a single program run.  Something like (assuming the bypass command is "noRamLim"):

```
noRamLim
R CMD BATCH myscript.R
```

**Comment by nariai** [comment]
Is something like below available to unlimit memory usage?
ulimit -v unlimited

**Comment by tatarsky** [comment]
Per Git #173 we used cgroups to limit the total RAM for a process. That is not by-passable with shell limits as the kernel is doing the work. cgroups always win. Which is why I use them for memory limits.

If you want that changed, we will need to re-discuss the desired limits. Which given the Notebook Hub use discussion, may not be needed. It only takes a moment to adjust. So if you would like it adjusted for Terry to be able to work, I can quickly do so and we can revisit later.

**Comment by tatarsky** [comment]
BTW when you say "access the Internet" I assume you mean an inbound access to something on the headnode. As the nodes NAT outbound connections. So a qlogin has full outbound access but if you are trying to "connect back" you need to play ssh tunnel games. Just checking in case thats an easier solution.

**Comment by tatarsky** [comment]
As a test of dynamically altering the cgroup I bumped fl-hn2 to 32GB. Just to confirm it worked. It appeared to but advise if we wish to continue having some limit or DISABLE limits. In general such limits reduce chaos on head nodes. But finding the right value is important.

**Comment by billgreenwald** [comment]
@nariai  and @s041629 and I talked and want to try to leave the 10GB and 32GB limit on flh1 and flh2 respectively for now and see if that fixes the issue we had.

**Comment by tatarsky** [comment]
Noted. Again easy to adjust, just advise "the limit".

**Comment by tatarsky** [comment]
Closed. Believed resolved generically by the fact fl-hn1 is running with no limits since cgroup removed and the Hub is taking most of the jobs to the nodes. Re-open if untrue.
