### ISSUE TITLE
jupyter hub died for (apparently) no reason

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#191]
Hi Paul,
I had a jupyter low job open for ~2 days and it suddenly died.
I have looked at the log with Bill and we couldn't figure out why. 

You can find the error log and output log in my home folder /frazer01/home/matteo/jupyterhub-singleuser.e2728908 and jupyterhub-singleuser.o2728908

thank you

**Comment by tatarsky** [comment]
The hub I show running so I assume you mean your job running via the hub. I will look when I have time at your logs and the node it was running on logs to see if I gain any insight.

Per #190 I am in and out.

**Comment by tatarsky** [comment]
However, this may be of use. If the job id is correct, the job appears to have exceeded the memory limit which is I believe for "juplow" we made 8GB.  Which is passed as the argument to qsub. We have no runtime limits on the queue "juplow" but we do have h_vmem enforcement.

```
qacct  -j 2728908 
==============================================================
qname        juplow.q            
hostname     fl-n-1-13           
group        users               
owner        matteo              
failed       37  : qmaster enforced h_rt, h_cpu, or h_vmem limit
maxvmem      16.012GB
arid         undefined
ar_sub_time  undefined
category     -l h_vmem=8G,juplow=TRUE -pe smp 2
```

I will confirm in a few minutes if your job was killed by that 8G limit on the node.

**Comment by tatarsky** [comment]
Confirmed. Job was killed due to exceeding 8GB vmem limit. Perhaps try a different Hub "type" or advise if you wish to adjust the "low" settings:

```04/13/2017 09:24:01|  main|fl-n-1-13|W|job 2728908.1 exceeds job hard limit "h_vmem" of queue "juplow.q@fl-n-1-13" (17192538112.00000 > limit:17179869184.00000) - sending SIGKILL
04/13/2017 09:24:02|  main|fl-n-1-13|W|job 2728908.1 exceeds job hard limit "h_vmem" of queue "juplow.q@fl-n-1-13" (17192538112.00000 > limit:17179869184.00000) - sending SIGKILL
```

**Comment by tatarsky** [comment]
We have a 16GB juplow choice as well  but that also probably would have been killed. Also the medium and high have more ram choices. So just advise if those defaults need to change but they require a restart of the master hub python.

**Comment by tatarsky** [comment]
As reminder I believe these are the Hub "session" options but remember they are selected at the start of the session.

https://github.com/frazer-lab/cluster/issues/175#issuecomment-281525573

**Comment by billgreenwald** [comment]
Thanks Paul--I didn't know about qacct.  Is there a way to kill the task without killing the job in the future?

**Comment by tatarsky** [comment]
Not sure I understand. The task and the job are the same thing. 

These Hub sessions are SGE qsubs (one per user). With the memory level the user chose when they first ran their session. (That chooser thing you and I defined the parameters for).

And all their notebooks spawed in that session are being run under that _same_ qsub. Aka subprocesses of that. On the node that runs the job. (Look at `qstat|grep jupyterhub` for example to see the jobs that involve the users running hub sessions....)

So when the session exceeds its memory limit (as defined by that qsub) SGE kills it. And any subshells. As it should. Because these are jobs running on nodes with other jobs and we only run up to the total memory limit of the nodes to prevent out of memory errors. We don't really want jobs running on nodes that exceed the memory they requested.

I guess I would instead make sure people pick the right "upper bound" of the qsub session and remember they are spawned qsubs with that limit for ALL notebooks. Or they should shutdown their session and re-open one with a bigger memory top limit. I wish the hub user view would say "This is a session with these Chosen values" but I don't see that as an option.

**Comment by tatarsky** [comment]
Also I believe lets say somebody started to do something with a "Low" hub session but then wants to run something that needs more resources (like Medium or High). I believe the "Hub way" for this would be to save and exit all your notebooks and shutdown your session. (The Control Panel button I believe exists for everyone but tell me if its admin only). That has a "Stop my session" and then you can use the Chooser to run a bigger session (which is a qsub again with that memory limit).

If this doesn't make sense perhaps a chat on a day I am more free. But I need some memory accounting controls on any job so that nodes are properly subscribed.

**Comment by tatarsky** [comment]
BTW, I generically understand it would be nice if the Hub actually spawed a qsub PER Notebook. But it does not. Its per user session. And I don't see any support for breaking it up but will scan the docs. So we might want to review and understand what sort of upper bound is "normal" on the memory needs....it would also be cool if we could hack in some kind of "you are using 10GB of your 16GB session max" sort of thing...

**Comment by s041629** [comment]
thanks!
