### ISSUE TITLE
java versions on CentOS 7 nodes?

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#224]
Hi Paul, It seems to me there has been a change in java versions on the new cluster, this is causing certain programs to have the "Unsupported major.minor version 52.0 error".  Do we have any idea what our old java configurations were? I want to replicate the java we had from the old cluster (I also know hn1 and hn2 were different on the old system).

Thanks!

**Comment by tatarsky** [comment]
I think the issue is that "52.0" means your item wants Java 1.8.

https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

```Thus, the 'major.minor version 52.0' error is possibly because the jar was compiled in jdk 1.8, but you are trying to run it using a jdk 1.7 environment. The reported number is the required number, not the number you are using```

**Comment by tatarsky** [comment]
I've currently only loaded on the C7 cluster as default Java 1.7 (OpenJDK version) because thats the default for CentOS 7.

I show on the old cluster at one point `fl-hn2` had OpenJDK 1.8 loaded. So I suspect thats the issue. `fl-hn1` had 1.7 loaded as were I believe the nodes. 

Probably makes the most sense to use Java 1.8 these days as a default and I can make modules for older versions. Do you want me to load Java 1.8 on say fl-hn1 and confirm these two comments with your code?

**Comment by tatarsky** [comment]
Assumed resolved.
