### ISSUE TITLE
Backup of lustre

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#23]
Opening this now so that we can track the main points of the conversion. We discussed eventually using raid3 as a backup for a subset of directory on the lustre. We are undecided on details (ZFS, images, etc.) but will decide later when we are ready to phase raid3 out of "normal" use.

**Comment by tatarsky** [comment]
Given the UPS outage at SDSC yesterday which did NOT impact us might be a good time however to review the plan for this in the light of the goal of stability and safety of data. 

As a reminder from the call I can export Lustre via NFS and also mount older servers to new systems due to the shared backend. I'll be out for a bit but happy to expound on various ways I use ZFS or just regular filesystems for backups. ZFS has a benefit of trivial snapshots....

**Comment by tatarsky** [comment]
While somehow its Thursday already this week, this should probably bump to a conversation at some point. Backups are a good thing and I see we are approaching 200TB on the /frazer filesystem.

**Comment by tatarsky** [comment]
This request is basically in early stages of handling via the `fl-nas1` box and no longer requires this Git request. Working directly with local sysadmins on the process.
