### ISSUE TITLE
Changes to jupyterhub

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#278]
Hi Paul,

We talked in lab meeting and want to make the following changes to the hub queues.  These apply to all jupHub queues (i think there are 2 juplo and juphi):

1) Can you remove the wall times from any that have it
2) Can you make the priority the same priority as short.q for both

Thanks!

**Comment by tatarsky** [comment]
For 1.
Walltimes were only set on juphigh.q
For reference they were:
s_rt                  172:00:00
h_rt                  172:10:00

They have been removed.

Working on 2.

**Comment by tatarsky** [comment]
For number 2. What are you seeing that you are trying to solve with that request? Do you want this because short.q jobs are flooding out requests for jupyter jobs and they can't get scheduled? 

I dimly recall from this battle:

https://github.com/frazer-lab/cluster/issues/24#issuecomment-296171156

That if I set them to the _same_ seq_no I see cases of wrong queue assignment. 
But I may have have fixed that another way with tagged PE (parallel execution) environments as I believe that was the root cause of that issue.

So I'll review the past so we don't revert something we discovered we needed but please just confirm the reason for wanting item 2.

**Comment by billgreenwald** [comment]
The reason is to allow notebooks to get on easily, yes. If it will cause
other problems though it's ok to just leave the current setting

**Comment by tatarsky** [comment]
I am pretty sure that comment I reference is "moot" based on my effort in the next item in the same discussion:

https://github.com/frazer-lab/cluster/issues/188#issuecomment-316693832

Where I believe I made sure that multiple slot juplow/juphigh would not attempt to poach PE slots from other queues. But I'm just reviewing what I did before I do anything ;)

I think in that case if I set them all to the same seq_no they all have the same priority. I can monitor that with qstat -pri but I'm going to read some old emails just to be sure on a Friday ;)

**Comment by billgreenwald** [comment]
Sounds good.  Just checking: do jobs currently in the jupHigh.q need to restart to not be effected by wall time, or will current jobs stay alive past the wall time

**Comment by tatarsky** [comment]
I believe walltime limits since they are really bash shell limits are applied when the job starts. 

So that shell already has the ulimit values in it. If you have a job id/pid you can check it but I'm pretty sure thats the case and there is no real SGE feature to "go back" and attempt to reset them.

**Comment by tatarsky** [comment]
Short version: I believe restart them.

**Comment by tatarsky** [comment]
I made the seq_no for the jup* queues the same as short.q 
Leaving open just to monitor for a bit. 

low was 1
high was 2

Both zero now.
