### ISSUE TITLE
httpd service

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#294]
It's not urgent, but can you check the service. I'll want to see /home/hiroko/public_html via http.

**Comment by tatarsky** [comment]
The reason it doesn't work is the password file is missing (due to Lustre loss)

```<Directory /frazer01/home/hiroko/public_html>
        AuthType Basic
        AuthName "Restricted"
        AuthUserFile /frazer01/home/hiroko/public_html/.htpasswd
        Options FollowSymLinks Indexes
        <LimitExcept OPTIONS>
                Require valid-user
        </LimitExcept>
</Directory>
```

Before I just remove that line I want to confirm you don't have things there you wish protected.

Same basic issue with others.

If you wish to re-create the password file, use the htpasswd command. (Can provide example)

**Comment by hirokomatsui** [comment]
I should have known that. Thanks!

**Comment by tatarsky** [comment]
Happy to remove the line...just advise. If you would like to remove:

/etc/httpd/conf.d/userdir.conf

Edit as needed. 

service httpd restart

**Comment by hirokomatsui** [comment]
No, let's keep that as it is.
