### ISSUE TITLE
Some questions by looking at GANGLIA

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#46]
Hi @tatarsky , just have a couple of questions while I'm looking at GANGLIA. 

I noticed CPU usage is close to 100% on each node, but only part of them is defined as User CPU (show as blue), and a large proportion of them are shown as red (system CPU). Not sure what's the difference between the two, and what is system doing using CPU. The load of each node is shown as red, supposedly because of the usage by system CPU?

Another question is if I check the network report from GANGLIA. What's the limit of the read/write speed in the current cluster? currently it's showing 100M byte/s for some nodes, and I do see it's gone up to 1G bytes/s some days ago. Just curious is there any limit of this number?

Thanks!

**Comment by tatarsky** [comment]
This would be a great topic for a Skype call ;)

Generically user cpu time is cpu instructions being done due to the processes code itself. System cpu time is usually related to code in your process that requires the kernel to do some work for you. (Disk I/O, networking, etc). Its calculated based on certain syscalls that the kernel does the execution of. 

You need to go over to a node to see more details usually with something like top/atop/htop to determine what processes are heavier system cpu v.s. user. It is normal for I/O related items to see what you are seeing there.

The networking "limit" depending on what graph you are looking at is the COMBINED total network capacity of a nodes 10Gbit/sec and 1Gbit/sec links. The Lustre traffic is on the 10Gbit side and the control traffic is on the 1Gbit/side. I do not show us anywhere near any maximum. Be careful Ganglia likes to display in bytes and has a set of multipliers that scale depending on the graph high point.

I find a different way of presenting network high water marks more useful than "aggregate all of it" and I'll make those graphs as a tab shortly. This is a partial answer due to some other items going on.

**Comment by tatarsky** [comment]
And one graph not yet available but of value is the network is only part of the picture for I/O. The disk statistics I hope to have available for viewing shortly on the Lustre servers. I can tell you nobody has managed yet to hit the high water marks I did during my tests. Although somebody gave it a good try back on the 7th.

**Comment by tatarsky** [comment]
Sorry 9th.

**Comment by hurleyLi** [comment]
Got it! Thanks!
