### ISSUE TITLE
Please state policy on compute jobs on head nodes

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#54]
The jobs running on the head node are in my opinion heavy for that systems role. I've noted several pauses this morning due to them as I work.

I do not know this groups view of such jobs. But I normally recommend they be performed via qlogin on a node or a scheduled job. 

Minimally a user should nice their jobs using the nice command to reduce impact on interactive use.

**Comment by djakubosky** [comment]
Apologies, I wasn't aware that these were slowing things down.  These jobs were initially run because there was heavy cluster use and was avoiding taking up space from Hurley's jobs.  If I were to kill half of them would that be okay for now?  

Update:
I'll kill most of them and try to submit them regularly.  I don't want anyones work impacted

**Comment by tatarsky** [comment]
I would simply have used nice/renice. Do you need an example?

**Comment by tatarsky** [comment]
Don't forget also head node 2 sits idle ;) If you need an item over there I've forgotten please advise.

**Comment by djakubosky** [comment]
I've never used nice, would appreciate the example

**Comment by tatarsky** [comment]
So nice is used when you first start a job and its default priority of 10 is reasonable:

```
nice (some process)
```

renice can be used on an already running job. but you need to provide a priority

```
renice 10 (some process id)
```

Alternately, top has a nice interface you can use as well.

Run top. Note your processes PID. Press the "r" key. It will ask you for a PID. Type its number. Then it will ask for a nice value. Enter 10. You can only renice your own processes.

Note clearly nice/renice are processor priority items only. It does not alter I/O.

**Comment by djakubosky** [comment]
Thanks for the tips, will re-nice the remaining things haha

Also, lab policy on using head nodes for things was different on the old cluster (where doing what I did would really bring everything down).  Generally people rarely ran on the head node- but since the system has only been seeing heavy use from a few lab members and because there are 2 head nodes I opted to run on the head node and send out a lab email letting people know that if things slowed down to tell me. 

Should such things always be run on head node 2?

Sorry I may have missed this piece of information somewhere along the way.

**Comment by tatarsky** [comment]
The above seems a fine policy statement. That is all I was looking for here. 

Some folks ask me to police head node jobs or impose limits on them. 

If the group is aware of your jobs and your willingness to nice them I'm all good. Matter as stated resolved! 

You can run the jobs I feel on head node 1 or 2 if it helps matters per the above. 

Advise if you are missing items.

**Comment by cdeboever3** [comment]
I wrote up a head node policy on the wiki. This is basically how we've managed shared interactive computers before.

https://github.com/frazer-lab/cluster/wiki#head-node-usage
