### ISSUE TITLE
Skype Today?

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#68]
Its ok if people are busy. But I am around. Primary topic would be next steps in efforts to merge some old nodes. But I believe we have everything ready and really its just a question of timing.

I am cycling back on a few items I am behind on. Git will be updated with status.

**Comment by nariai** [comment]
It turned out that some of the lab members need to use the old cluster for urgent matters (expected to be finished by the end of next week), let's hold on merging the old nodes for the moment.

Given that, I guess we can skip the skype meeting today. Next week, we can update the situation and resume discussion for merging the old nodes again. If others have something to discuss, I'm happy to organize the call.

**Comment by tatarsky** [comment]
Sounds logical to me! Closing. If change your mind just re-open with a time!
